### ISSUE TITLE
App Crashing when installing using one signal

### ISSUE THREAD

**Issue by ajmahesh-12** [OneSignal/OneSignal-Android-SDK#899]
App is crashing when installing using Onesignal cordova plugin on android 9.0. Its working absolutely fine on android 6.0
After removing the plugin app works fine.

Also when building apk. its giving compilation error when 
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
is placed before any apply plugin

When commented this line 
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

build is created but crashing on android 9.0 or higher.But working fine on android 6.0

PLEASE HELP

Here is the logcat file

11-24 12:36:55.136    1441-1802/? E/WindowManager﹕ win=Window{c74f47a u0 Splash Screen com.osr.hairbookprobusiness EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5375 com.android.server.wm.WindowStateAnimator.onAnimationFinished:319 com.android.server.wm.WindowState.onAnimationFinished:5797 com.android.server.wm.-$$Lambda$yVRF8YoeNdTa8GR1wDStVsHu8xM.run:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0:92
11-24 12:36:55.844  10060-10189/? E/AndroidRuntime﹕ FATAL EXCEPTION: OS_REST_SUCCESS_CALLBACK
    Process: com.osr.hairbookprobusiness, PID: 10060
    java.lang.IllegalArgumentException
            at android.os.Parcel.createException(Parcel.java:1970)
            at android.os.Parcel.readException(Parcel.java:1934)
            at android.os.Parcel.readException(Parcel.java:1884)
            at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:1888)
            at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:577)
            at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:565)
            at com.onesignal.NotificationChannelManager.createChannel(NotificationChannelManager.java:177)
            at com.onesignal.NotificationChannelManager.processChannelList(NotificationChannelManager.java:218)
            at com.onesignal.OneSignal$5.complete(OneSignal.java:1011)
            at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:139)
            at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:11)
            at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:79)
            at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:262)
            at java.lang.Thread.run(Thread.java:764)
     Caused by: android.os.RemoteException: Remote stack trace:
            at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:33)
            at com.android.server.notification.RankingHelper.createNotificationChannel(RankingHelper.java:632)
            at com.android.server.notification.NotificationManagerService$12.createNotificationChannelsImpl(NotificationManagerService.java:2585)
            at com.android.server.notification.NotificationManagerService$12.createNotificationChannels(NotificationManagerService.java:2600)
            at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:292)
11-24 12:36:55.943    1441-2000/? E/InputDispatcher﹕ channel 'fe91a2e com.osr.hbpbusiness/com.osr.hbpbusiness.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-24 12:36:55.945    1441-2000/? E/InputDispatcher﹕ channel '961618 com.osr.hbpbusiness/com.osr.hbpbusiness.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-24 12:36:55.945    1441-2000/? E/InputDispatcher﹕ channel '5e59656 com.osr.hbpbusiness/com.osr.hbpbusiness.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-24 12:36:55.961    1441-1576/? E/WindowManager﹕ RemoteException occurs on reporting focusChanged, w=Window{5e59656 u0 com.osr.hbpbusiness/com.osr.hbpbusiness.MainActivity EXITING}
    android.os.DeadObjectException
            at android.os.BinderProxy.transactNative(Native Method)
            at android.os.BinderProxy.transact(Binder.java:1145)
            at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)
            at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3889)
            at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5456)
            at android.os.Handler.dispatchMessage(Handler.java:106)
            at android.os.Looper.loop(Looper.java:214)
            at android.os.HandlerThread.run(HandlerThread.java:65)
            at com.android.server.ServiceThread.run(ServiceThread.java:44)
11-24 12:36:55.963    1441-3768/? E/WindowManager﹕ win=Window{fe91a2e u0 com.osr.hbpbusiness/com.osr.hbpbusiness.MainActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5375 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:2403 com.android.server.wm.AppWindowToken.setVisibility:551
11-24 12:36:55.966    1441-3768/? E/WindowManager﹕ win=Window{961618 u0 com.osr.hbpbusiness/com.osr.hbpbusiness.MainActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5375 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:2403 com.android.server.wm.AppWindowToken.setVisibility:551
11-24 12:36:56.270    1441-1802/? E/WindowManager﹕ win=Window{5e59656 u0 com.osr.hbpbusiness/com.osr.hbpbusiness.MainActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5375 com.android.server.wm.WindowStateAnimator.onAnimationFinished:319 com.android.server.wm.WindowState.onAnimationFinished:5797 com.android.server.wm.-$$Lambda$yVRF8YoeNdTa8GR1wDStVsHu8xM.run:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0:92

**Comment by jkasten2** [comment]
Duplicate of #895

**Comment by remoideas** [comment]
It´s a bug when you have categories on settings/categories, remove all and thats work.

**Comment by ajmahesh-12** [comment]
Could you please provide step by step instructions and/or screenshots
