### ISSUE TITLE
Unknown error getting FCM Token Failed resolution of FirebaseInstanceId

### ISSUE THREAD

**Issue by chokokatana** [OneSignal/OneSignal-Android-SDK#1346]
**Description:**

After upgrading firebase BOM from 27.1.0 to 28.0.1 I had to update my source code since [FirebaseInstanceId is deprecated](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId). After doing the changes I see such logs at runtime:
```
2021-05-25 11:58:37.852 6555-6725/E/OneSignal: Unknown error getting FCM Token
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
        at com.onesignal.PushRegistratorFCM.getToken(PushRegistratorFCM.java:60)
        at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:97)
        at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37)
        at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/data/app/…
```

Are these runtime warnings/errors a problem?

**Steps to Reproduce Issue:**

1. Change firebase bom to 28.0.1.

**Comment by jkasten2** [comment]
@chokokatana @SufyanQadeer OneSignal-Android-SDK 4.3.4 and older is not compatible with Firebase Messaging 22.0.0. We will have an update soon but until then you can continue using 21 or older. We will update this when the release is available.

**Comment by jkasten2** [comment]
A fix is now included in release OneSignal-Android-SDK 4.4.0
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.4.0
