### ISSUE TITLE
IllegalStateException on OSNotificationRestoreWorkManager related with WorkManager

### ISSUE THREAD

**Issue by salihaksit7** [OneSignal/OneSignal-Android-SDK#1369]
**Description:**

After upgrading version to 4.4.0, this _(WorkManager is not initialized properly..)_ crash appears on bugsnag. I could not reproduce it. But it affects %0.01 of our users from almost all api versions above 21.
I seen this closed issue [#1336](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1336), and checked if default implementation disabled but it was not.

The merged Manifest : 
```
        <provider
            android:name="androidx.work.impl.WorkManagerInitializer"
            android:exported="false"
            android:multiprocess="true"
            android:authorities="{myApplicationId}.workmanager-init"
            android:directBootAware="false" />
```
Libraries who depends on 'androidx.work:work-runtime:' : 
- com.google.android.gms:play-services-ads:20.1.0
- com.onesignal:OneSignal:4.4.0

**Stacktrace**
```java
Caused by: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
        at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl:156)
        at androidx.work.WorkManager.getInstance(WorkManager:184)
        at com.onesignal.OSNotificationRestoreWorkManager.beginEnqueueingWork(OSNotificationRestoreWorkManager:48)
        at com.onesignal.OneSignal.onAppFocusLogic(OneSignal:1354)
        at com.onesignal.OneSignal.onAppFocus(OneSignal:1339)
        at com.onesignal.ActivityLifecycleHandler.handleFocus(ActivityLifecycleHandler:182)
        at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler:88)
        at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener:91)
        at android.app.Application.dispatchActivityResumed(Application.java:216)
        at android.app.Activity.onResume(Activity.java:1313)
        at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity:433)
        at {myApplicationId}.ui.main.MainActivity.onResume(MainActivity:203)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
        at android.app.Activity.performResume(Activity.java:7117)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3572)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3637)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2878)
        at android.app.ActivityThread.-wrap11(Unknown)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6543)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
```
**Environment**

- classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.10'
- implementation "com.onesignal:OneSignal:4.4.0"
- implementation "androidx.work:work-runtime:2.5.0"
- implementation "androidx.multidex:multidex:2.0.1"
- implementation "androidx.core:core-ktx:1.5.0"

**Application & NotificationHandler Class**
```
class MyApplication : MultiDexApplication() {

    override fun onCreate() {
        super.onCreate()

        Bugsnag.start(this)

        MobileAds.initialize(this) {}

        OneSignal.initWithContext(this)
        OneSignal.setAppId("my_app_id")
        OneSignal.setNotificationWillShowInForegroundHandler { notificationReceivedEvent: OSNotificationReceivedEvent ->
            notificationReceivedEvent.complete(
                null
            )
        }
        OneSignal.unsubscribeWhenNotificationsAreDisabled(false)
        OneSignal.setNotificationOpenedHandler(DeepLinkNotificationOpenHandler(this))
    }
}
```
```
internal class DeepLinkNotificationOpenHandler(private val appContext: Context) : OneSignal.OSNotificationOpenedHandler {
    override fun notificationOpened(result: OSNotificationOpenedResult) {
        val intent = Intent(appContext, MainActivity::class.java)
        intent.flags = Intent.FLAG_ACTIVITY_REORDER_TO_FRONT or Intent.FLAG_ACTIVITY_NEW_TASK
        val data = result.notification.additionalData
        if (data != null && data.has("notificationDeepLink")) {
            val notificationDeepLink = data.getString("notificationDeepLink")
            intent.putExtra("notificationDeepLink", notificationDeepLink)
        }
        appContext.startActivity(intent)
    }
}
```

**Comment by emawby** [comment]
@salihaksit7 Thank you for the report, I believe this is caused by the "android:multiprocess="true"" setting based off of [this](https://programmerr47.medium.com/custom-work-manager-initialization-efdd2afa6459) blogpost I found. I am still looking into workarounds and potential fixes from OneSignal's side.

**Comment by AndreFerreira18** [comment]
Hi. I'm facing the same issue on my production environment, commenting here to follow up. Thanks in advance for any help @emawby .

**Comment by emawby** [comment]
@AndreFerreira18 I am still looking for a solution from our end. Does you app also use "android:multiprocess="true"? Did you try any of the workarounds suggested in the [blog post](https://programmerr47.medium.com/custom-work-manager-initialization-efdd2afa6459)

**Comment by AndreFerreira18** [comment]
Hi @emawby . The app does not use "android:multiprocess="true" and I've implemented the solution provided at the end of the blog post in my latest release. Unfortunately, the error has occured on that release.

**Comment by emawby** [comment]
@AndreFerreira18 that is good to know I am assuming you are not able to reproduce the issue?

**Comment by AndreFerreira18** [comment]
Yes @emawby. Unfortunately I can't reproduce the issue but my userbase can 😓

**Comment by emawby** [comment]
@AndreFerreira18 what version of workmanager are you using is it "androidx.work:work-runtime:2.5.0"? Can you try updating to the latest version.
