### ISSUE TITLE
Not able to import android.support.v4.media

### ISSUE THREAD

**Issue by mnk98** [OneSignal/OneSignal-Android-SDK#1128]
**Description:**

When i upgrade my onesignal sdk from 3.13.0 to above version like 3.13.2 or 3.15.*, then `import android.support.v4.media` this gives me error and said do not found.

**Environment**

1. I am using OneSignal Android SDK 3.13.0
1. The SDK is added through maven
1. My project is using other firebase services like analytics and crashlytics
1. My project is using exoplayer 2 and give me error in this file https://github.com/android/uamp/blob/master/common/src/main/java/com/example/android/uamp/media/extensions/MediaMetadataCompatExt.kt for `import android.support.v4.media.` 

**Steps to Reproduce Issue:**

1. Use the project https://github.com/android/uamp/
1. Add the OneSignal SDK to your project through gradle with latest version
3.Added google-services.json to project
1. Initialize OneSignal in application class.
1. You will see error that can not import `import android.support.v4.media.`

**Anything else:**

(crash stacktraces, as well as any other information here)

e: common/src/main/java/com/example/android/uamp/media/extensions/MediaMetadataCompatExt.kt:205: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()

**Comment by Jeasmine** [comment]
Hey @mnk98 did you try using the onesignal gradle plugin https://github.com/OneSignal/OneSignal-Gradle-Plugin? This will help you with version conflicts. Let me know if that didn't help

**Comment by mnk98** [comment]
Yes, i am using `classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.6' `

**Comment by Jeasmine** [comment]
Can I ask for your builg.gradle?

**Comment by mnk98** [comment]
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
        maven { url 'https://maven.fabric.io/public' } //CrashLytics
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.6' 
        classpath 'io.fabric.tools:gradle:1.30.0' //CrashLytics
    }
}

repositories {
    maven { url 'https://maven.google.com/' }
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'androidx.navigation.safeargs'
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: 'com.google.gms.google-services' //CrashLytics
//// Apply the Crashlytics Gradle plugin
//apply plugin: 'com.google.firebase.crashlytics'


dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation deps.support.app_compat
    implementation deps.support.recyclerview
    implementation deps.support.cardview
    implementation deps.support.design
    implementation deps.navigation.fragment_ktx
    implementation deps.navigation.ui
    implementation deps.room.runtime
    implementation deps.lifecycle.runtime
    implementation deps.lifecycle.extensions
    implementation deps.lifecycle.java8
    implementation deps.retrofit.runtime
    implementation deps.retrofit.gson
    implementation deps.glide.runtime
    implementation deps.dagger.runtime
    implementation deps.dagger.android
    implementation deps.dagger.android_support
    implementation deps.constraint_layout
    implementation deps.kotlin.stdlib
    implementation deps.timber
    kapt deps.dagger.android_support_compiler
    kapt deps.dagger.compiler
    kapt deps.room.compiler
    kapt deps.lifecycle.compiler

    implementation 'androidx.core:core-ktx:1.5.0-alpha02'

    // Testing
    testImplementation deps.junit
    testImplementation deps.mock_web_server
    testImplementation(deps.arch_core.testing, {
        exclude group: 'com.android.support', module: 'support-compat'
        exclude group: 'com.android.support', module: 'support-annotations'
        exclude group: 'com.android.support', module: 'support-core-utils'
    })

    // Google analytic
    implementation 'com.google.android.gms:play-services-analytics:17.0.0' //11.8.0

    // full exoplayer library
    implementation 'com.google.android.exoplayer:exoplayer:2.9.1'
    implementation 'com.google.android.exoplayer:extension-ima:2.9.1'
    implementation 'com.google.android.exoplayer:extension-mediasession:2.9.1'
    implementation 'org.greenrobot:eventbus:3.1.1' 


    // OneSignal
    implementation ('com.onesignal:OneSignal:3.13.0'){ 
        exclude group: 'com.google.android.gms'
    }

    implementation 'com.google.firebase:firebase-messaging:20.2.4'
    implementation 'com.google.firebase:firebase-iid:20.2.4'
    implementation 'com.google.android.gms:play-services-location:17.0.0' 

    //CrashLytics
    implementation('com.crashlytics.sdk.android:crashlytics:2.10.1@aar') { 
        transitive = true
    }
    implementation 'com.google.firebase:firebase-core:17.5.0' 

    implementation 'com.android.support:design:28.0.0'

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.0" 
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.0" 


    // Recommended: Add the Firebase SDK for Google Analytics.
    implementation 'com.google.firebase:firebase-analytics-ktx:17.5.0'

    // Add the Firebase Crashlytics SDK.
    implementation 'com.google.firebase:firebase-crashlytics-ktx:17.2.1'

}

**Comment by nan-li** [comment]
@mnk98 Sorry it has been a while, is this still an issue for you?

**Comment by nan-li** [comment]
@mnk98 Closing due to no response, this is an old issue and haven't seen any more reports.

Please feel free to comment and we can re-open in the future.
